name: deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs:
  deploy:
    name: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          set-safe-directory: '*'

      - name: Setup Ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.x # Use the version of Ruby that you need

      - name: Install Bundler
        run: gem install bundler
        env:
          GEM_HOME: ${{ github.workspace }}/vendor/bundle
          BUNDLE_PATH: ${{ github.workspace }}/vendor/bundle

      - name: Caching for Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build and deploy
        uses: Hamza-Aziz/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
